# Generated by Django 3.2.24 on 2024-02-13 19:47

from django.db import migrations, models
import upload_file.validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', validators=[upload_file.validators.FileValidator(max_size=1048576)]),
        ),
    ]
